steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - -c
      - >-
        docker build
        --file=Dockerfile
        --build-arg=firebase_api_key=$$NEXT_PUBLIC_FIREBASE_API_KEY
        --build-arg=firebase_auth_domain=$$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        --build-arg=firebase_project_id=$$NEXT_PUBLIC_FIREBASE_PROJECT_ID
        --build-arg=firebase_storage_bucket=$$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        --build-arg=firebase_messaging_sender_id=$$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        --build-arg=firebase_app_id=$$NEXT_PUBLIC_FIREBASE_APP_ID
        --build-arg=firebase_measurement_id=$$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
        --build-arg=database_url=$$DATABASE_URL
        .
    secretEnv:
      [
        'NEXT_PUBLIC_FIREBASE_API_KEY',
        'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN',
        'NEXT_PUBLIC_FIREBASE_PROJECT_ID',
        'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET',
        'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
        'NEXT_PUBLIC_FIREBASE_APP_ID',
        'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID',
        'DATABASE_URL',
      ]
availableSecrets:
  secretManager:
    - versionName: projects/651805024697/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_API_KEY'
    - versionName: projects/651805024697/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
    - versionName: projects/651805024697/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_PROJECT_ID'
    - versionName: projects/651805024697/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'
    - versionName: projects/651805024697/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'
    - versionName: projects/651805024697/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_APP_ID'
    - versionName: projects/651805024697/secrets/NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID'
    - versionName: projects/651805024697/secrets/DATABASE_URL/versions/latest
      env: 'DATABASE_URL'
