steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - -c
      - >-
        docker build
        --file=Dockerfile
        --build-arg=firebase_api_key=$$NEXT_PUBLIC_FIREBASE_API_KEY
        --build-arg=firebase_auth_domain=$$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        --build-arg=firebase_project_id=$$NEXT_PUBLIC_FIREBASE_PROJECT_ID
        --build-arg=firebase_storage_bucket=$$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        --build-arg=firebase_messaging_sender_id=$$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        --build-arg=firebase_app_id=$$NEXT_PUBLIC_FIREBASE_APP_ID
        --build-arg=firebase_measurement_id=$$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
        --build-arg=nextauth_secret=$$NEXTAUTH_SECRET
        --build-arg=nextauth_url=$$NEXTAUTH_URL
        --build-arg=database_url=$$DATABASE_URL
        --build-arg=discord_client_id=$$DISCORD_CLIENT_ID
        --build-arg=discord_client_secret=$$DISCORD_CLIENT_SECRET
        --build-arg=google_client_id=$$GOOGLE_CLIENT_ID
        --build-arg=google_client_secret=$$GOOGLE_CLIENT_SECRET
        --build-arg=github_client_id=$$GITHUB_CLIENT_ID
        --build-arg=github_client_secret=$$GITHUB_CLIENT_SECRET
        -t gcr.io/$PROJECT_ID/${_IMAGE_NAME}
        .
    secretEnv:
      [
        'NEXT_PUBLIC_FIREBASE_API_KEY',
        'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN',
        'NEXT_PUBLIC_FIREBASE_PROJECT_ID',
        'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET',
        'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
        'NEXT_PUBLIC_FIREBASE_APP_ID',
        'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID',
        'NEXTAUTH_SECRET',
        'NEXTAUTH_URL',
        'DATABASE_URL',
        'DISCORD_CLIENT_ID',
        'DISCORD_CLIENT_SECRET',
        'GOOGLE_CLIENT_ID',
        'GOOGLE_CLIENT_SECRET',
        'GITHUB_CLIENT_ID',
        'GITHUB_CLIENT_SECRET',
      ]
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}']
  - name: gcr.io/cloud-builders/gcloud
    id: 'deploy-cloud-run'
    args:
      [
        'beta',
        'run',
        'deploy',
        '${_SERVICE_NAME}',
        '--image',
        'gcr.io/$PROJECT_ID/${_IMAGE_NAME}',
        '--platform',
        'managed',
        '--region',
        'asia-northeast1',
        '--allow-unauthenticated',
        '--port',
        '3000',
      ]
substitutions:
  _IMAGE_NAME: 'full-stack'
  _SERVICE_NAME: 'full-stack'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_PROJECT_ID'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_APP_ID'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID'
    - versionName: projects/$PROJECT_ID/secrets/NEXTAUTH_SECRET/versions/latest
      env: 'NEXTAUTH_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/NEXTAUTH_URL/versions/latest
      env: 'NEXTAUTH_URL'
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: 'DATABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/DISCORD_CLIENT_ID/versions/latest
      env: 'DISCORD_CLIENT_ID'
    - versionName: projects/$PROJECT_ID/secrets/DISCORD_CLIENT_SECRET/versions/latest
      env: 'DISCORD_CLIENT_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_ID/versions/latest
      env: 'GOOGLE_CLIENT_ID'
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_SECRET/versions/latest
      env: 'GOOGLE_CLIENT_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/GITHUB_CLIENT_ID/versions/latest
      env: 'GITHUB_CLIENT_ID'
    - versionName: projects/$PROJECT_ID/secrets/GITHUB_CLIENT_SECRET/versions/latest
      env: 'GITHUB_CLIENT_SECRET'
