name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  packages:
    name: check npm install
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ./.tool-versions
          cache: npm
      - name: check npm ci
        run: npm ci
  lint:
    name: run lint
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ./.tool-versions
          cache: npm
      - name: npm ci
        run: npm ci
      - name: run lint
        run: npm run lint -- --max-warnings=0
  format:
    name: run format
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ./.tool-versions
          cache: npm
      - name: npm ci
        run: npm ci
      - name: run format
        run: npx prettier --check .
  test:
    name: run test
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ./.tool-versions
          cache: npm
      - name: npm ci
        run: npm ci
      - name: run test
        run: npm run test
  build:
    name: run build
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ./.tool-versions
          cache: npm
      - name: npm ci
        run: npm ci
      - name: run build
        run: npm run build
